### ISSUE TITLE
Error: Unknown element TextInput

### ISSUE THREAD

**Issue by Serif-x** [mimecorg/vuido#11]
If I try `TextInput` widget, an error will throw after running `npm run start`, but build command before that is okay.

```
Error: Unknown element TextInput
    at Object.createElement (.\dist\main.js:6484:30)
    at createElm (.\dist\main.js:3600:79)
    at createChildren (.\dist\main.js:3708:9)
    at createElm (.\dist\main.js:3619:9)
    at createChildren (.\dist\main.js:3708:9)
    at createElm (.\dist\main.js:3619:9)
    at VueComponent.patch [as __patch__] (.\dist\main.js:4064:7)
    at VueComponent.Vue._update (.\dist\main.js:717:19)
    at VueComponent.updateComponent (.\dist\main.js:822:10)
    at Watcher.get (.\dist\main.js:2373:27)
```

Thanks for your attention.

**Comment by mimecorg** [comment]
That's because TextInput didn't exist in version 0.1.0. I will add a few more widgets and publish a new version by the end of this week.
