### ISSUE TITLE
App closed after Cancel an open file Dialog

### ISSUE THREAD

**Issue by atilacamurca** [mimecorg/vuido#21]
I'm trying to run this, but if I hit the `Cancel` button of the open file dialog I'm getting an error and my app close unexpectedly.

```vue
<template>
  <Window ref="mainWindow">
    <Button @click="selectFile">Browse...</Button>
  </Window>
</template>
<script>
import libui from 'libui-node'

export default {
    methods: {
        selectFile () {
            const window = this.$refs.mainWindow.window
            const filename = libui.UiDialogs.openFile(window)
            if (filename) {
                console.log(filename)
            }
        }
    }
}
</script>
```

The error is:

```
[...]/dist/main.js:120
            const filename = __WEBPACK_IMPORTED_MODULE_0_libui_node___default.a.UiDialogs.openFile(window);
                                                                                          ^

Error: basic_string::_M_construct null not valid
    at VueComponent.selectFile ([...]/dist/main.js:120:91)
    at invoker ([...]/dist/main.js:2589:18)
```

**Comment by parro-it** [comment]
I think this a problem related to [libui-node](https://github.com/parro-it/libui-node).
Would you mind post an issue there?

**Comment by atilacamurca** [comment]
related to https://github.com/parro-it/libui-node/issues/116

**Comment by mimecorg** [comment]
This is fixed is libui-node, I will update Vuido to use version 0.2.1.
