### ISSUE TITLE
Could not locate bindings for midi-node

### ISSUE THREAD

**Issue by VojtechKlos** [mimecorg/vuido#61]
Hello, I was just trying vuido by creating a simple app to control your mouse with midi using [midi](https://www.npmjs.com/package/midi) and [robotjs](https://www.npmjs.com/package/@morajabi/robotjs) packages. I can build the main.js file with npm run build but when i try to run it (after build) with npm start it shows following error:

```
Error: Could not locate the bindings file. Tried:
 → C:\Users\vojtik\projects\midimouse-vuido\build\midi.node
 → C:\Users\vojtik\projects\midimouse-vuido\build\Debug\midi.node
 → C:\Users\vojtik\projects\midimouse-vuido\build\Release\midi.node
 → C:\Users\vojtik\projects\midimouse-vuido\out\Debug\midi.node
 → C:\Users\vojtik\projects\midimouse-vuido\Debug\midi.node
 → C:\Users\vojtik\projects\midimouse-vuido\out\Release\midi.node
 → C:\Users\vojtik\projects\midimouse-vuido\Release\midi.node
 → C:\Users\vojtik\projects\midimouse-vuido\build\default\midi.node
 → C:\Users\vojtik\projects\midimouse-vuido\compiled\10.16.2\win32\x64\midi.node
 → C:\Users\vojtik\projects\midimouse-vuido\addon-build\release\install-root\midi.node
 → C:\Users\vojtik\projects\midimouse-vuido\addon-build\debug\install-root\midi.node
 → C:\Users\vojtik\projects\midimouse-vuido\addon-build\default\install-root\midi.node
 → C:\Users\vojtik\projects\midimouse-vuido\lib\binding\node-v64-win32-x64\midi.node
    at bindings (C:\Users\vojtik\projects\midimouse-vuido\dist\main.js:383:9)
    at Object../node_modules/midi/midi.js (C:\Users\vojtik\projects\midimouse-vuido\dist\main.js:568:86)
    at __webpack_require__ (C:\Users\vojtik\projects\midimouse-vuido\dist\main.js:20:30)
    at Module../node_modules/babel-loader/lib/index.js!./node_modules/vue-loader/lib/index.js?!./src/MainWindow.vue?vue&type=script&lang=js& (C:\Users\vojtik\projects\midimouse-vuido\dist\main.js:159:14)
    at __webpack_require__ (C:\Users\vojtik\projects\midimouse-vuido\dist\main.js:20:30)
    at Module../src/MainWindow.vue?vue&type=script&lang=js& (C:\Users\vojtik\projects\midimouse-vuido\dist\main.js:9182:193)
    at __webpack_require__ (C:\Users\vojtik\projects\midimouse-vuido\dist\main.js:20:30)
    at Module../src/MainWindow.vue (C:\Users\vojtik\projects\midimouse-vuido\dist\main.js:9148:98)
    at __webpack_require__ (C:\Users\vojtik\projects\midimouse-vuido\dist\main.js:20:30)
    at Module../src/main.js (C:\Users\vojtik\projects\midimouse-vuido\dist\main.js:9216:69)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! midimouse@1.0.0 start:dev: `node ./dist/main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the midimouse@1.0.0 start:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\vojtik\AppData\Roaming\npm-cache\_logs\2019-11-10T14_08_26_356Z-debug.log
```

I tried rebuilding all the libraries (midi and robotjs), removing node_modules folder and npm install again, even npm cache clear --force but to no success. I tried the same code with electron and it worked fine so I am not really sure how to work this out with vuido and I am not really sure if vuido is the source of the problem either. Any help would be appreciated. Thanks.

**Comment by VojtechKlos** [comment]
BTW I added node-loader to webpack because it could not build without it.
